version: "3.3"

services:

  #-------------- APP
  app:
    image: justdimmy/fintech:latest
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      - PORT
      - NODE_ENV
      - IS_DRY_RUN
      - CHECK_ON_START
      - BASE_URL
      - TOKEN
      - DELAY
      - DAYS
      - SLOW
      - FAST
      - DB_HOST
      - DB_PORT
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - SENTRY_DSN
      - HTTP_USER
      - HTTP_PASS
    logging:
      options:
        max-size: "10M"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  #-------------- DB
  db:
    image: postgres:12.3-alpine
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10M"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

